# curl --location --request PATCH 'http://localhost:3000/users?id=cf577fd7-3fd3-4266-80d9-45d9e19f068b'
#--header 'Content-Type: application/json'
#--data '{
#    "name": "User"
#}'
PATCH http://localhost:3000/users?id=cf577fd7-3fd3-4266-80d9-45d9e19f068b
Content-Type: application/json

{
  "name": "User"
}

###

# curl --location 'http://localhost:3000/users'
#--header 'Content-Type: application/json'
#--data '{
#    "name": "Mittal"
#}'
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Mittal"
}

###

# curl --location 'http://localhost:3000/users'
GET http://localhost:3000/users

###

# curl --location 'http://localhost:3000/users/cf577fd7-3fd3-4266-80d9-45d9e19f068b'
GET http://localhost:3000/users/cf577fd7-3fd3-4266-80d9-45d9e19f068b

###

# curl --location --request PATCH 'http://localhost:3000/posts?id=05574427-6b1b-47dc-80a0-67f641f61ced'
#--header 'Content-Type: application/json'
#--data '{
#    "title": "Nation",
#    "content": "True Nation",
#    "isPublished": false,
#    "authorId":"8069bc13-8021-4b41-ae1e-11eb61502bf5"
#}'
PATCH http://localhost:3000/posts?id=05574427-6b1b-47dc-80a0-67f641f61ced
Content-Type: application/json

{
  "title": "Nation",
  "content": "True Nation",
  "isPublished": false,
  "authorId": "8069bc13-8021-4b41-ae1e-11eb61502bf5"
}

###

# curl --location 'http://localhost:3000/posts'
GET http://localhost:3000/posts

###

# curl --location 'http://localhost:3000/posts/a8f211c9-1652-4ce5-a909-c881797af89c'
GET http://localhost:3000/posts/a8f211c9-1652-4ce5-a909-c881797af89c

###

# curl --location 'http://localhost:3000/posts'
#--header 'Content-Type: application/json'
#--data '{
#    "title": "Nation",
#    "content": "Nation",
#    "isPublished": false,
#    "authorId":"8069bc13-8021-4b41-ae1e-11eb61502bf5"
#}'
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Nation",
  "content": "Nation",
  "isPublished": false,
  "authorId": "8069bc13-8021-4b41-ae1e-11eb61502bf5"
}

###

# curl --location 'http://localhost:3000/products'
#--header 'Content-Type: application/json'
#--data '{
#    "name": "Dates",
#    "price": "299.9"
#}'
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "GroundNut",
  "price": "209.9"
}

###

# curl --location --request PATCH 'http://localhost:3000/products?id=1689d347-d283-4ab0-ae8a-ae4099c2195b'
#--header 'Content-Type: application/json'
#--data '{
#    "name": "FlexSeeds",
#    "price": "200.8"
#}'
PATCH http://localhost:3000/products?id=1689d347-d283-4ab0-ae8a-ae4099c2195b
Content-Type: application/json

{
  "name": "FlexSeeds",
  "price": "200.8"
}

###

### Get product by id
GET http://localhost:3000/products?id={{productId}}
Accept: application/json

### Get all products
GET http://localhost:3000/products


